export * from './IGoods';
export * from './IInput';
export * from './IGetMinMaxValue';
export * from './IAllGoods';
export * from './IAuth';
export * from './IStates';
export * from './ICart';
export * from './IAdmin';
export * from './IDispatch';
